services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - TZ=Europe/Rome
    volumes:
      - ./ha-config:/config
    ports:
      - "8123:8123"
    privileged: true
    restart: unless-stopped

  broker:
    image: heycasa/broker
    container_name: broker
    environment:
      - TZ=Europe/Rome
    network_mode: host
    privileged: true
    restart: unless-stopped
